WITH global_head AS
  (SELECT gh_ouid FROM mfi.MV_CNG_CURRENT WHERE ORG_RIAD_CODE = '{0}'
  )

SELECT ORG_OUID ,
  ORG_RIAD_CODE ,
  ORG_COUNTRY_CODE ,
  ORG_ORGUNIT_NAME ,
  ORG_ESA_SECTOR_NEW ,
  ORG_ESA_SECTOR ,
  ORG_LEGAL_FORM ,
  ORG_LEI ,
  ORG_BIC
FROM mfi.MV_CNG_CURRENT
WHERE ORG_OUID = (SELECT gh_ouid FROM global_head)